def viewAll(b):
		print("Nama           : ",end="")
		print(b[0][0])
		print("Umur           : ",end="")
		print(b[0][1])
		print('Jenis Kelamin  : ',end="")
		print(b[0][2])
		print('No.KTP         : ',end="")
		print(b[0][3])
		print('Alamat         : ',end="")
		print(b[0][4])
		print("Nama Dokter    : ",end="")
		print(b[1][0])
		print("Keluhan Pasien : ", end="")
		print(b[1][1])